# Generated by Django 2.0.3 on 2018-04-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180403_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(max_length=10)),
                ('humidity', models.CharField(max_length=10)),
                ('lighting', models.CharField(max_length=10)),
                ('ph', models.CharField(max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Humidity',
        ),
        migrations.DeleteModel(
            name='Lighting',
        ),
        migrations.DeleteModel(
            name='Ph',
        ),
        migrations.DeleteModel(
            name='Temperature',
        ),
    ]
