# Generated by Django 2.0.3 on 2018-03-16 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='temperature',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
